{
    "scssLint.showHighlights": true,
    "scssLint.runOnTextChange": true,
    "scssLint.errorBackgroundColor": "rgba(200, 0, 0, .8)",
    "scssLint.warningBackgroundColor": "rgba(200, 120, 0, .8)",
    "scssLint.languages": [
        "scss"
    ],
    "scssLint.statusBarText": "`$(telescope) scss-lint  ${errors.length} $(x)  ${warnings.length} $(alert)`",
    "scssLint.configDir": ""
}
