export const ADD_PROS = "ADD_PROS";
export const REMOVE_PROS = "REMOVE_PROS";
export const RENAME_PROS = "REMOVE_PROS";

export const ADD_CONS = "ADD_CONS";
export const REMOVE_CONS = "REMOVE_CONS";
export const RENAME_CONS = "REMOVE_CONS";

export const FETCH_LINKS_START = "FETCH_LINKS_START";
export const FETCH_LINKS_SUCCESS = "FETCH_LINKS_SUCCESS";
export const FETCH_LINKS_FAILURE = "FETCH_LINKS_FAILURE";

export const ECOMMERCE_SIDEBAR_MENU_LINKS_START =
 "ECOMMERCE_SIDEBAR_MENU_LINKS_START";
export const ECOMMERCE_SIDEBAR_MENU_LINKS_SUCCESS =
 "ECOMMERCE_SIDEBAR_MENU_LINKS_SUCCESS";
export const ECOMMERCE_SIDEBAR_MENU_LINKS_FAILURE =
 "ECOMMERCE_SIDEBAR_MENU_LINKS_FAILURE";
